import FWCore.ParameterSet.Config as cms

def GetSampleFiles(sampleName, filesOpt):
    if sampleName == 'QCD_noPU' :
        filesOpt.outputFile = cms.string("$CMSSW_BASE/src/FastTiming/RecoTreeUtils/ntuples/QCD_noPU.root")
        
        #filesOpt.inputFiles = cms.untracked.vstring("file:/afs/cern.ch/user/s/spigazzi/work/FastTiming_TP/PR_CMSSW620_SLHC23/outfiles4test/PhoJet_RAWRECO_noPU_bugfix.root")

        filesOpt.inputFiles = cms.untracked.vstring(
            "root://eoscms//eos/cms/store/relval/CMSSW_6_2_0_SLHC25_patch3/RelValQCDForPF_14TeV/GEN-SIM-RECO/DES23_62_V1_UPGFastTime-v1/00000/06EF5738-07DD-E411-B6DD-0025905822B6.root",
            "root://eoscms//eos/cms/store/relval/CMSSW_6_2_0_SLHC25_patch3/RelValQCDForPF_14TeV/GEN-SIM-RECO/DES23_62_V1_UPGFastTime-v1/00000/98086D73-15DD-E411-9FBF-0025905B8606.root",
            "root://eoscms//eos/cms/store/relval/CMSSW_6_2_0_SLHC25_patch3/RelValQCDForPF_14TeV/GEN-SIM-RECO/DES23_62_V1_UPGFastTime-v1/00000/D842A30F-05DD-E411-8289-003048FFCBFC.root",
            "root://eoscms//eos/cms/store/relval/CMSSW_6_2_0_SLHC25_patch3/RelValQCDForPF_14TeV/GEN-SIM-RECO/DES23_62_V1_UPGFastTime-v1/00000/DEF24673-15DD-E411-BB52-0025905A6076.root")
        
    if sampleName == "QCD_140PU" :        
        filesOpt.outputFile = cms.string("$CMSSW_BASE/src/FastTiming/RecoTreeUtils/ntuples/QCD_140PU.root")

        filesOpt.inputFiles = cms.untracked.vstring(*(
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_1.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_10.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_100.root",   
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_101.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_102.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_103.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_104.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_105.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_106.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_107.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_108.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_109.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_11.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_110.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_111.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_112.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_113.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_114.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_115.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_116.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_117.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_118.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_119.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_12.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_120.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_121.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_122.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_123.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_124.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_125.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_126.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_127.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_128.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_129.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_13.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_130.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_131.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_132.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_133.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_134.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_135.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_136.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_137.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_138.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_139.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_14.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_140.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_141.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_142.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_143.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_144.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_145.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_146.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_147.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_148.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_149.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_15.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_150.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_151.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_152.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_153.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_154.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_155.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_156.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_157.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_158.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_159.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_16.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_160.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_161.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_162.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_163.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_164.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_165.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_166.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_167.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_168.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_169.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_17.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_170.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_171.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_172.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_173.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_174.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_175.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_176.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_177.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_178.root",  
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_179.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_18.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_180.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_181.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_182.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_183.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_184.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_185.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_186.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_187.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_188.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_189.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_19.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_190.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_191.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_192.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_193.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_194.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_195.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_196.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_197.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_198.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_199.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_2.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_20.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_200.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_21.root",  
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_22.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_23.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_24.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_25.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_26.root",
            #"root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_27.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_28.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_29.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_3.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_30.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_31.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_32.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_33.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_34.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_35.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_36.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_37.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_38.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_39.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_4.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_40.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_41.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_42.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_43.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_44.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_45.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_46.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_47.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_48.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_49.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_5.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_50.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_51.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_52.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_53.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_54.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_55.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_56.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_57.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_58.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_59.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_6.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_60.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_61.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_62.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_63.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_64.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_65.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_66.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_67.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_68.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_69.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_7.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_70.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_71.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_72.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_73.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_74.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_75.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_76.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_77.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_78.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_79.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_8.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_80.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_81.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_82.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_83.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_84.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_85.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_86.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_87.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_88.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_89.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_9.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_90.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_91.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_92.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_93.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_94.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_95.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_96.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_97.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_98.root",
            "root://eoscms//eos/cms/store/user/amartell/fastTiming/QCD_Pt_15to500_Tune4C_RAWRECO_PU140inTime/QCD_14TeV_upgradePLS3_RAWRECO_99.root"))    

    if sampleName == "H125GG_noPU" :
        filesOpt.outputFile = cms.string("$CMSSW_BASE/src/FastTiming/RecoTreeUtils/ntuples/H125GG_noPU.root")
            
        filesOpt.inputFiles = cms.untracked.vstring(
            "root://eoscms//eos/cms/store/relval/CMSSW_6_2_0_SLHC25_patch3/RelValH130GGgluonfusion_14TeV/GEN-SIM-RECO/DES23_62_V1_UPGFastTime-v1/00000/96E49372-15DD-E411-B452-0025905B858E.root",
            "root://eoscms//eos/cms/store/relval/CMSSW_6_2_0_SLHC25_patch3/RelValH130GGgluonfusion_14TeV/GEN-SIM-RECO/DES23_62_V1_UPGFastTime-v1/00000/CCD4AD73-15DD-E411-92AA-0025905AA9F0.root",
            "root://eoscms//eos/cms/store/relval/CMSSW_6_2_0_SLHC25_patch3/RelValH130GGgluonfusion_14TeV/GEN-SIM-RECO/DES23_62_V1_UPGFastTime-v1/00000/DEC52010-08DD-E411-B622-0025905A60B2.root")

    if sampleName == "MinBias" :
        filesOpt.outputFile = cms.string("$CMSSW_BASE/src/FastTiming/RecoTreeUtils/ntuples/MinBias.root")
        
        filesOpt.inputFiles = cms.untracked.vstring(
            "root://eoscms//eos/cms/store/relval/CMSSW_6_2_0_SLHC25_patch3/RelValMinBias_TuneZ2star_14TeV/GEN-SIM-RECO/DES23_62_V1_UPGFastTime-v1/00000/3E875ECC-05DD-E411-82A7-003048FFCBFC.root",
            "root://eoscms//eos/cms/store/relval/CMSSW_6_2_0_SLHC25_patch3/RelValMinBias_TuneZ2star_14TeV/GEN-SIM-RECO/DES23_62_V1_UPGFastTime-v1/00000/A6E3B9A7-05DD-E411-A9E0-0025905A60A6.root")
        
    if sampleName == "PhoJet_140PU" :
        filesOpt.outputFile = cms.string("$CMSSW_BASE/src/FastTiming/RecoTreeUtils/ntuples/PhoJet_140PU.root")
            
        filesOpt.inputFiles = cms.untracked.vstring(
            "file:/afs/cern.ch/user/s/spigazzi/work/FastTiming_TP/CMSSW_6_2_0_SLHC25_patch1/MC_samples/PhoJet/nRAWRECO_140PU_0_numEvent50.root",
            "file:/afs/cern.ch/user/s/spigazzi/work/FastTiming_TP/CMSSW_6_2_0_SLHC25_patch1/MC_samples/PhoJet/nRAWRECO_140PU_1_numEvent50.root",
            "file:/afs/cern.ch/user/s/spigazzi/work/FastTiming_TP/CMSSW_6_2_0_SLHC25_patch1/MC_samples/PhoJet/nRAWRECO_140PU_2_numEvent50.root",
            "file:/afs/cern.ch/user/s/spigazzi/work/FastTiming_TP/CMSSW_6_2_0_SLHC25_patch1/MC_samples/PhoJet/nRAWRECO_140PU_3_numEvent50.root",
            "file:/afs/cern.ch/user/s/spigazzi/work/FastTiming_TP/CMSSW_6_2_0_SLHC25_patch1/MC_samples/PhoJet/nRAWRECO_140PU_4_numEvent50.root",
            "file:/afs/cern.ch/user/s/spigazzi/work/FastTiming_TP/CMSSW_6_2_0_SLHC25_patch1/MC_samples/PhoJet/nRAWRECO_140PU_5_numEvent50.root",
            "file:/afs/cern.ch/user/s/spigazzi/work/FastTiming_TP/CMSSW_6_2_0_SLHC25_patch1/MC_samples/PhoJet/nRAWRECO_140PU_6_numEvent50.root",
            "file:/afs/cern.ch/user/s/spigazzi/work/FastTiming_TP/CMSSW_6_2_0_SLHC25_patch1/MC_samples/PhoJet/nRAWRECO_140PU_7_numEvent50.root",
            "file:/afs/cern.ch/user/s/spigazzi/work/FastTiming_TP/CMSSW_6_2_0_SLHC25_patch1/MC_samples/PhoJet/nRAWRECO_140PU_8_numEvent50.root",
            "file:/afs/cern.ch/user/s/spigazzi/work/FastTiming_TP/CMSSW_6_2_0_SLHC25_patch1/MC_samples/PhoJet/nRAWRECO_140PU_9_numEvent50.root")
    
