import FWCore.ParameterSet.Config as cms

process = cms.PSet()

process.ioFiles = cms.PSet(
    inputFiles = cms.vstring("/afs/cern.ch/user/s/spigazzi/work/FastTiming_TP/CMSSW_6_2_0_SLHC23/outfile4test/SingleJet/RAW-RECO_noPU.root"),
    
    outputFile = cms.string('outfile4test/QCD_noPU.root')
)

process.ioFilesB = cms.PSet(
    outputFile = cms.string('outfile4test/QCD_140PU.root'),

    inputFiles = cms.vstring("root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_1.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_10.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_100.root",   
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_101.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_102.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_103.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_104.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_105.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_106.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_107.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_108.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_109.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_11.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_110.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_111.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_112.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_113.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_114.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_115.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_116.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_117.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_118.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_119.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_12.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_120.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_121.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_122.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_123.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_124.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_125.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_126.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_127.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_128.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_129.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_13.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_130.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_131.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_132.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_133.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_134.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_135.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_136.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_137.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_138.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_139.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_14.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_140.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_141.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_142.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_143.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_144.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_145.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_146.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_147.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_148.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_149.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_15.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_150.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_151.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_152.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_153.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_154.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_155.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_156.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_157.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_158.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_159.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_16.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_160.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_161.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_162.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_163.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_164.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_165.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_166.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_167.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_168.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_169.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_17.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_170.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_171.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_172.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_173.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_174.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_175.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_176.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_177.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_178.root",  
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_179.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_18.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_180.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_181.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_182.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_183.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_184.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_185.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_186.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_187.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_188.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_189.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_19.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_190.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_191.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_192.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_193.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_194.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_195.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_196.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_197.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_198.root",
                             "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_199.root")
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_2.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_20.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_200.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_21.root",  
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_22.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_23.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_24.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_25.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_26.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_27.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_28.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_29.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_3.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_30.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_31.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_32.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_33.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_34.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_35.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_36.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_37.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_38.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_39.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_4.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_40.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_41.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_42.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_43.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_44.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_45.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_46.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_47.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_48.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_49.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_5.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_50.root")
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_51.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_52.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_53.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_54.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_55.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_56.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_57.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_58.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_59.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_6.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_60.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_61.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_62.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_63.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_64.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_65.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_66.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_67.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_68.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_69.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_7.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_70.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_71.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_72.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_73.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_74.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_75.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_76.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_77.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_78.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_79.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_8.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_80.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_81.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_82.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_83.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_84.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_85.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_86.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_87.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_88.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_89.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_9.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_90.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_91.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_92.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_93.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_94.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_95.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_96.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_97.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_98.root",
                             # "root://eoscms//eos/cms/store/caf/user/amartell/fastTiming/QCD_Pt15_500_14TeV_Tune4C_RECO_PU140inTime/QCD_14TeV_upgradePLS3_RECO_140PUinTime_99.root")
    
)

process.ioFilesB = cms.PSet(
    outputFile = cms.string('outfile4test/SingleGamma_noPU.root'),
    
    inputFiles = cms.vstring(
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_1.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_10.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_100.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_11.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_12.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_13.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_14.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_15.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_16.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_17.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_18.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_19.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_2.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_20.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_21.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_22.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_23.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_24.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_25.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_26.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_27.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_28.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_29.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_3.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_30.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_31.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_32.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_33.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_34.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_35.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_36.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_37.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_38.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_39.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_4.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_40.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_41.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_42.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_43.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_44.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_45.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_46.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_47.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_48.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_49.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_5.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_50.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_51.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_52.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_53.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_54.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_55.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_56.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_57.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_58.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_59.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_6.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_60.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_61.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_62.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_63.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_64.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_65.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_66.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_67.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_68.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_69.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_7.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_70.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_71.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_72.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_73.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_74.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_75.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_76.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_77.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_78.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_79.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_8.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_80.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_81.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_82.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_83.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_84.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_85.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_86.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_87.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_88.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_89.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_9.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_90.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_91.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_92.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_93.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_94.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_95.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_96.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_97.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_98.root",
        "root://eoscms//eos/cms/store/user/amartell/fastTiming/SingleGammaE50_noPU/SingleGammaE50_noPU_DIGIRECO_99.root")
)
